user:
  firstName: kiruthika kittusamy96
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true  
      
  endpoints:
    web:
      exposure:
        include:
        - "*"
